# Generated by Django 4.0.3 on 2022-03-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_detail_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('rank', models.IntegerField(null=True)),
                ('gmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.subject')),
            ],
        ),
    ]
